example.organization.property: "I AM THE DEFAULT ORGANIZATION SERVICE"

server:
  port: 8081

#datasourceP配置
spring.datasource.driver-class-name: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql:///eagle_eye_dev?serverTimezone=UTC"
spring.datasource.username: "root"
spring.datasource.password: "root"

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.thoughtmechanix.organization.model

management.endpoints.web.exposure.include: refresh,health,info

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
          binder: kafka
      kafka:
        binder:
          brokers: 106.15.72.10
          zkNodes: 106.15.72.10
