#spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
#spring.jpa.show-sql: "true"
spring.datasource.driver-class-name: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql:///eagle_eye_dev?serverTimezone=UTC"
spring.datasource.username: "root"
spring.datasource.password: "root"
#spring.datasource.testWhileIdle: "true"
#spring.datasource.validationQuery: "SELECT 1"
#spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
#redis.server: "redis"
#redis.port: "6379"
#signing.key: "345345fsdfsf5345"

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.thoughtmechanix.licenses.model

management.endpoints.web.exposure.include: refresh,health,info

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
          binder: kafka
      kafka:
        binder:
          brokers: 106.15.72.10:9092
          zk-nodes: 106.15.72.10:2181